### PR TITLE
Use re-factored ondemand-packaging

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
@johrstrom This is ready for review.  Once the final changes are merged, I will go to other repos and make identical changes.

**Comment by treydock** [comment]
@johrstrom If these kind of changes look good,  I can make similar changes to other repos to get them using refactored ondemand-packaging

**Comment by johrstrom** [comment]
Sure - but I guess we should cut a release just to be sure it works for sure?

**Comment by treydock** [comment]
Either a new release or the package building part can be tested using a pull request I think, if the mirror on code.osu.edu is setup correctly.

**Pull request merged**
